### ISSUE TITLE
Cannot build admin UI from sources

### ISSUE THREAD

**Issue by drakulis** [sulu/skeleton#52] opened 2020-04-21 16:41 UTC
| Q | A
| --- | ---
| Bug? | YES
| New Feature? | NO
| Sulu Version | 2.0.6
| Browser Version | irrelevant

#### Actual Behavior

I'm not able to build admin UI using files in the repo. I'm getting lots of errors related to `scss` compilation.
![obraz](https://user-images.githubusercontent.com/1709738/79889635-9a302600-83fe-11ea-8550-ceed3d2ee4a7.png)

#### Expected Behavior

I should be able to build admin UI 😄 

#### Steps to Reproduce

* Checkout the repo 
* navigate to `./assets/admin` directory
* execute `npm install`
* execute `npm run build`

#### Possible Solutions
The problem here is missing `package-lock.json`
Please commit correct `package-lock.json` with proper versions of dependencies locked. I found one which works for me here: https://github.com/sulu/sulu-workshop-symfony-live-berlin-2019/blob/master/assets/admin/package-lock.json

When I've copied this file to `./assets/admin` directory and installed node_modules I was finally able to build the project

**Comment by alexander-schranz** [comment] 2020-04-21 17:03
If you just want the admin build which is locked for your sulu version you should use the `bin/console sulu:admin:download-build` command.

NPM is sometimes a little bit bitchy could you try to remove all `package-lock.json` and `node_modules` in `assets/admin` and `vendor/sulu/sulu`? 

Easiest way to achive this is doing the following in the project root directory:

```
rm -rf ./**/package-lock.json
rm -rf ./**/node_Modules
```

And then try again:

```
npm install
npm run build
```

If you still get an error please provide which version of `node` and `npm` you are using?

**Comment by drakulis** [comment] 2020-04-21 17:35
Thanks for answer. Indeed when I removed all `node_modules` from `vendor/sulu` i was able to built the project

I want to extend UI with my own features that's why I would like to be able to build it by myself. I have used bunch of node/npm versions - 6, 8, 10, 12 (each time removed node_modules from `assets/admin` first) but none was working. Right now I stick to:
node - 8.17.0
npm - 6.13.4

The thing is that `package-lock.json` HAS TO BE commited for admin UI project (`assets/admin`) and it CANNOT BE commited for particular packages in `vendor/sulu/sulu` (it is not now as i see). Otherwise I'm pretty sure more users will struggle with this issue

**Comment by nnatter** [comment] 2020-04-22 12:48
@sulu/core-team Should we commit a `package-lock.json` file in this repository? Do you see any disadvantages of this?

**Comment by alexander-schranz** [comment] 2020-04-22 12:55
I must say that the `package-lock.json` would make this issue worse. I'm switching because of different projects between node versions and a `package-lock.json` created with node 12 does not work correctly with node 10 or vise verse.
So having no package-lock.json and the package-lock.json is created correctly for the version which the developer use is better here I think else we must force a specific node and npm version.
And as it did work after he cleared the node_modules and package-lock.json this totally seems to be the issue that before another node/npm version was used to create the package-lock.json.

**Comment by danrot** [comment] 2020-04-22 17:13
I guess the real problem here was that NPM creates also `node_modules` folders in the `vendor` folders, because of the weird way it handles dependencies. I am not even sure if that would be solved with a `package-lock.json` file, but I am with @alexander-schranz here. Pinning to a certain node and NPM version would make it even harder to get your own build working.

Personally I even have disabled the `package-lock.json` file, because it is just one more ingredient that could make your build fail (I've disabled it because this was the reason multiple times).

I am going to close this issue for now, but feel free to suggest more solutions, but I don't see anything else working because of how node is working. Deleting everything by using the `rm -r **/node_modules` command in the root of this project is usually your best bet. You might think that `npm update` should also work, but the last time I tried that caused other weird behavior, but maybe that was fixed in a later version.

**Closed by danrot** 2020-04-22 17:13 UTC

**Comment by drakulis** [comment] 2020-04-22 18:56
@alexander-schranz @danrot 

Guys I'm also switching node version depends on project I'm working on. But this is not a reason for me to not commit `package-lock.json`. This is my duty as a developer to use proper tools.
This file has been invented to prevent issues like the one described here.
We should rather lock node and npm version in `package.json` in `engines` node https://docs.npmjs.com/files/package.json#engines
This way user has to use proper version - otherwise will get nice and verbose error.

Allowing user to use whatever node/npm version is really terrible approach, especially that it doesn't concern some server environment but development one, where developer may use proper tools which are required by the project.

**Comment by danrot** [comment] 2020-04-22 20:46
If we only allow a single version of node many people will struggle, because they don't have the correct version installed, and not everybody is using something like nvm.

Also, the build is executed regularly, and usually does not make any problems. I also don't think that a lock file will solve this error. However, i am still giving it a try tomorrow and see if I can get an acceptable behavior by using a lock file.

**Comment by drakulis** [comment] 2020-04-22 21:53
Well, if developer doesn't know how to switch node/npm version on his local machine then he should change the job 😉. Node/React.js/Angular/Vue/whatever.js developer has to know how to do it nowadays, otherwise he should not touch the code at all.

> I also don't think that a lock file will solve this error

It was! 😃. As I mentioned before as soon as I copied lock file from here https://github.com/sulu/sulu-workshop-symfony-live-berlin-2019/blob/master/assets/admin/package-lock.json 
and installed dependencies, the build process succeed - without removing anything from `vendor` directory - not sure what Node/NPM version I was using then but it was not working without this file.

**Comment by danrot** [comment] 2020-04-23 06:47
> Well, if developer doesn't know how to switch node/npm version on his local machine then he should change the job . Node/React.js/Angular/Vue/whatever.js developer has to know how to do it nowadays, otherwise he should not touch the code at all.

People might start learning React because they want to use Sulu, so I think we should not make it harder for them to do so than necessary. Demanding a certain version of Node and NPM would do so. We just demand a minimum version, because we need a certain behavior when using `file:` dependencies.

> > I also don't think that a lock file will solve this error
> 
> It was so! . As I mentioned before as soon as I copied lock file from here https://github.com/sulu/sulu-workshop-symfony-live-berlin-2019/blob/master/assets/admin/package-lock.json
> and installed dependencies, the build process succeed - without removing anything from `vendor` directory - not sure what Node/NPM version I was using then but it was not working without this file.

We were using the `package-lock.json` file for quite some time, and it was causing more harm than good. I haven't tried to reproduce myself right now, but I did a quick research, and there are still quite some issues open regarding the `package-lock.json` file in their repositories.

E.g. in [this issue](https://github.com/npm/npm/issues/17722) is explained that not only different node versions, but also different operating systems might cause troubles. In [a comment to another issue](https://github.com/npm/cli/issues/944#issuecomment-590678762) one of the contributors states that deleting the `package-lock.json` file and executing `npm install` is the easiest way to solve problems. Then there are quite some other issues concering the `package-lock.json`, just putting some of them here (npm/cli#961, npm/cli#716, npm/cli#409, npm/npm#18613, whereby the last one seems to be a bit exaggerating, but the person seems to ended up adding the `package-lock.json` to their `.gitignore` file as well, so there are also other opinions than yours).

Additionally to these technical issues, there is also the fact that we don't commit a `composer.lock` file either, for similar conceptual reasons. Composer would also install different versions of packages when you are using different PHP versions, and therefore weird behaviour might be caused. Because of this we also don't commit a `composer.lock` file, because we don't want to tell everybody which exact PHP version should be used in their project.

There are also plenty of people recommending to commit lock files only in individual projects, not in a library or product. That is because our product must work with different set of dependencies, especially with the newest available dependencies described in `composer.json` or `package.json`, because that is what people are receiving when they are updating the application. And since our dependencies are not a closed set, but can be extended in every project, that is even more important.

**Comment by drakulis** [comment] 2020-04-23 12:55
I see your point. I agree that `fsevents` (and other OS specific packages) could be pain in the ass. I'm also aware that this is template project which should be used as a base for final portals so you don't want to restrict tools for users.

Even though this template (without any modifications) should work out of the box. Right now it is not. Well, not for everybody 😉. I've struggled with this issue about two days, probably because I've used node v12 for compilation at the beginning (not sure now, just guessing). 
So from my point of view something like this should be added to README.md:

```
Here is our template SULU project which you may start working on.
It has been implemented and tested using following tools:
- PHP: v7.2
- Composer: vXXX
- Symfony: v4.3
- NodeJS: vXXX
- NPM: vXXX

If you like you may change tools recommended by us to your own 
but be aware that if you experience problems you have to solve them by your own.
```
Right now I can see there only info about PHP and Symfony.

As for `package-lock.json`, you are worried that it will be changed when user execute `npm install`. Sure it may happen especially when he use different NPM major version. But it doesn't matter. It is already his final project. He may commit it to own repo. But even if lock file is changed, the dependencies are still locked, so user may work on packages which were working for you during Sulu  Skeleton implementation.

Please don't get me wrong. I'm not kind of smart-ass. I just see some gaps in current setup and I want to help you somehow fill them out to spare such problems for other users.

**Comment by danrot** [comment] 2020-04-24 08:41
We already have a [system requirements page in our documentation](https://docs.sulu.io/en/2.0/reference/requirements.html?highlight=npm#development-requirements). And we don't really want to specify the tooling, it should just work for all of our compatible ones.

It is just that we had a terrible experience when we were commiting these files, that's why I don't really want to add them again. And to be fair, if you are switching the node version during some of these steps, you would probably struggle with or without a `package-lock.json` file.

So if we would introduce this `package-lock.json` file, it would be trading some set of problems for other problems. And since our experience improved a lot since we have removed that file, I don't really see us adding it again.

And I don't get you wrong, your suggestions are highly appreciated :slightly_smiling_face: It is just that it seems like we've made different experiences in that regard.
